FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .a

# dengarkan PORT dari Railway
CMD ["waitress-serve", "--host=0.0.0.0", "--port=8080", "app:app"]

